# Generated by Django 4.0.6 on 2022-07-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingbooth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('college', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
                ('conform_password', models.CharField(max_length=50)),
            ],
        ),
    ]
