# Generated by Django 4.0.6 on 2022-07-06 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollingbooth', '0002_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee', models.CharField(max_length=500)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.position')),
            ],
        ),
    ]
