# Generated by Django 4.0.5 on 2022-07-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollingbooth', '0003_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('prn_number', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('conform_password', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.college')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.year')),
            ],
        ),
    ]
