# Generated by Django 3.2 on 2022-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingbooth', '0003_nominee'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='type',
            field=models.CharField(default='student', max_length=100),
            preserve_default=False,
        ),
    ]
