# Generated by Django 3.2 on 2022-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingbooth', '0004_authority_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='branch',
            field=models.ManyToManyField(to='pollingbooth.Branch'),
        ),
    ]
