# Generated by Django 3.2 on 2022-07-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollingbooth', '0005_election_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.position'),
        ),
    ]
