# Generated by Django 4.0.5 on 2022-07-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollingbooth', '0005_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_post', models.CharField(max_length=50)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election')),
            ],
        ),
    ]
