# Generated by Django 4.0.6 on 2022-07-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingbooth', '0008_alter_authority_type_alter_result_total_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='type',
        ),
        migrations.AddField(
            model_name='authority',
            name='typeLogin',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
