# Generated by Django 4.0.6 on 2022-07-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingbooth', '0009_remove_authority_type_authority_typelogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='typeLogin',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
