# Generated by Django 4.0.5 on 2022-06-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College_Election_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Election_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Election_of_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_of_branch', models.CharField(max_length=50)),
                ('election_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election_level')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Election_Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('prn_number', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('election_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election_level')),
                ('election_of_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election_of_department')),
                ('election_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.college_election_position')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Election_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_position', models.CharField(max_length=50)),
                ('election_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election_level')),
                ('election_of_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election_of_department')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Election_Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50)),
                ('election_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election_level')),
                ('election_of_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election_of_department')),
                ('election_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.department_election_position')),
            ],
        ),
        migrations.CreateModel(
            name='College_Election_Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('prn_number', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('election_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election_level')),
                ('election_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.college_election_position')),
            ],
        ),
        migrations.AddField(
            model_name='college_election_position',
            name='election_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election_level'),
        ),
        migrations.CreateModel(
            name='College_Election_Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50)),
                ('election_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.election_level')),
                ('election_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingbooth.college_election_position')),
            ],
        ),
    ]
