# Generated by Django 3.2.13 on 2022-07-05 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('college_id', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_item', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('token_number', models.CharField(max_length=8)),
                ('name_of_item', models.ManyToManyField(to='canteentokensystem.MenuItems')),
                ('name_of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteentokensystem.userdetails')),
            ],
        ),
    ]
