# Generated by Django 3.2.13 on 2022-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteentokensystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
