# Generated by Django 3.2.13 on 2022-07-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteentokensystem', '0002_auto_20220705_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='image',
            field=models.ImageField(default=1, upload_to='menu'),
            preserve_default=False,
        ),
    ]
