# Generated by Django 3.2.13 on 2022-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteentokensystem', '0003_menuitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_admin',
            field=models.BooleanField(default=0),
        ),
    ]
