# Generated by Django 3.2.13 on 2022-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteentokensystem', '0005_feedbackmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmessage',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
