# Generated by Django 4.0.5 on 2022-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingbooth', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=50)),
            ],
        ),
    ]
